name: CI

on:
  push:
    branches: "main"
  pull_request:

jobs:
  luacheck:
    name: luacheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install luacheck
        run: |
          sudo apt-get update
          sudo apt-add-repository universe
          sudo apt install luarocks -y
          sudo luarocks install luacheck

      - name: Run luacheck
        run: make lint

  stylua:
    name: stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install cargo
        uses: actions-rs/cargo@v1.0.1
        with:
          command: install
          args: stylua --features lua52

      - name: Run stylua
        run: make check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        run: |
          sudo apt-get update
          sudo add-apt-repository universe
          wget https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
          chmod u+x nvim.appimage
          sudo ./nvim.appimage --appimage-extract
          sudo mv ./squashfs-root /opt/nvim
          sudo ln -s /opt/nvim/AppRun /usr/local/bin/nvim
          git clone https://github.com/nvim-lua/plenary.nvim.git ~/.local/share/nvim/site/pack/plenary.nvim/start/plenary.nvim
      - name: Test
        continue-on-error: false
        run: |
          make test
